vim.cmd('abb teh the')
vim.cmd('abb Teh The')
vim.cmd('abb compnay company')
vim.cmd('abb cliet client')
vim.cmd('abb cleint client')
vim.cmd('abb clinet client')
vim.cmd('abb jif {% if %}')
vim.cmd('abb jiffield {% if case.get_field(\'\') %}')
vim.cmd('abb jendif {% endif %}')
vim.cmd('abb jelif {% elif %}')
vim.cmd('abb jelse {% else %}')
vim.cmd('abb casefield {{case.get_field(\'\')}}')
vim.cmd('abb taht that')
